spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yyx-mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.macro.mall: debug
  config: classpath:logback.xml

aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tRyQqWqHbFnNYVmCCoX # 访问身份验证中用到用户标识
    accessKeySecret: e48psaPBYfFwwbttQXKjLkjW5U4j2P # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: hl-mall-tiny # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    #callback:  # 文件上传成功后的回调地址
    dir:
      prefix: hlmall/images/ # 上传文件夹路径前缀

wxmini:
  appid: 'wx8bf84902e3987b1c'
  secret: 'da25fa0e5e0f7c6e98c3852e79097252'
  msgDataFormat: JSON

alipay:
  appId: 2021000121686745
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCG7chNEoEaOd1XLbYnvT2AoAhwHEW4D2p8ge2yea98ncFBhUmLKGMcPUmn4XVNGWMY+8Oql0NxJ8gUF7dZnweDqPnUiGseoafKKWavpOVyXvyUfgALBrsojrNJpwplLKuVBxakC1fycRIzewgwv8IiihgSketJZyRivT35/sw2xhKKo2uluB/5h13vp9Cn8mGfvO8dXUfId3Xat2htlTgO1oMue1blJ+xbAsgIZjl/TGqeRJCETO9BSfHggRarMAiW5s0/y5IQ9liVDEoDzatpS5nmJeRjetlw/TIxX71TRR5Od4qYfcXpRE+fM3S8ipIRIWDzfaEsb/ck97Ru2nXvAgMBAAECggEAGYLFt0TDYhkEr2H2KcdO5I3daoz95ZIMmSPbtD3rnw0Yp/GyePwW2RUBYxtumTguk1+unAdjefaCjsH5KZm2yv7c1YFBd5Yq6j8vqg/sTdaFvPGhwnPwWPe6EDfj8EMk4dVoQ3Xdl/om7dLaNpVa+DrR2Fj8enFk4MJVAHpbVBOSuqqqIJ5gvZoGa1h72aafP0zrqfR3jdCLobzzDH6/BQqjj52LacmyDQhScRu7wL1MksMCtz6gk9FoUw0WZrX3lroTYGFGpVsPgdaGUnJnaKG44duYLDv+MWHGaicKo2wThsW20nH2oCNg8c46NRcrWbPDqlxR0RtvKUff/JFPMQKBgQDDMyswMl2HpSouyy4UrqPV/XX7yeGm064t4EKnGnseGNKEnYJ8SAsnh15dTz4AUio6QYvC9ghQFwoLLcG+311EYFRytqvPuLBrgoWUrQRm7U0HoZJ18UlChxQT2Gu6i6FwzgLYyMbCbVhc3ZVXPyJyYfiMT/7kGoZb2M8dNYyB5wKBgQCw9LoEt0txl5jUX+/9LK3Kdok/6nby81aGgsKA9YQD8RBwpXxFyq+6VkTKuN1AIQaPUKTwTQQlIw9oqWvTQ/RaivRnlVyveBM/4WACMgRL69iGgBE7AX03ru0xWzdjUK8f4Sk7PU0BQCwjPe0ejsDkL4TICItRIetA/3JXikP6uQKBgQC1EGa0S1O0ukEZrMBu0NwKaBSj3UziCaKczVQmWwrvDQlhmBVsoQsvvIKMvS9+7rha12gEDWICoIxheC0ql1iVT2GmEsnmYaPL5gNwuNjHfMEiHf6URp+1BUVbbznmjRTQZVgArKSpvvHjGmsnxdl3DmeWB7Ig9nXBBqh/qKdP6wKBgFw2q9lZS09emJ3TgNSGO+qN6ugL3wCsHiLqcUGSr8D+FnsdQa18+iY4XpDl1SZeD3UPqWQwPkC8DIOWBkKJ3wRv9P0lsK8f+6gGYmnCdsq5lJRCmLgPBpnF5oUZ67stiJUsWLguMbq9HkMfOjn6WjqPKLq0+STGcDnm5EcKHnLBAoGBALayHdWx3ZSKTd+HdOBQ8B0vzYzkCLGx8o010OzRCHIWFTReIQKlx29R2+n/basltXQYZte+Tym6ltDazT7RMCbB1GORCXuec7EIv5aJVAzQcVsJvSB2tGNwoKgCSBoTLzC8p3zociGGU72uYyfH+rx8L3Sv64yNaBDCEpzsccUN
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqNTQoNZ69ySa/p7y8q+iD0qPqmsyvXUd8xc1n9x05ZK+2NAy0oi11MTyXjl2gW/uaKhYU1hVLJd/3DxFxN227gr9ZtlCTEcC6FB1CWw1MiDIBYHYj1JfQcD2lzDaVc6qR1ttm7O8rjg743R8hMmAOc6jkcREX/5MOIi7d7jKdXw8e5l70lQ/lDq+voz3XmheZr+NmFNqsSNI5Re7hshWjgZvpBAdMH3PbwWxqRiQ27d4JPqaz007JQejNXvogKXpEbc8eq/G/9RGRYQ5DJndkIFA1nA860xqodUxL9TpUu6ZOoTPVcwu7LfyDrFFy3743mrmPmcPC43f6rSN30HTCQIDAQAB
  notifyUrl: http://hl243695czyn.free.idcfengye.com/alipay/notify